//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleClient.Encap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockedOut {
            get {
                return this.LockedOutField;
            }
            set {
                if ((this.LockedOutField.Equals(value) != true)) {
                    this.LockedOutField = value;
                    this.RaisePropertyChanged("LockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/Soap_Basic.Responses")]
    [System.SerializableAttribute()]
    public partial class UserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SampleClient.Encap.User> UserListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasSuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SampleClient.Encap.User> UserList {
            get {
                return this.UserListField;
            }
            set {
                if ((object.ReferenceEquals(this.UserListField, value) != true)) {
                    this.UserListField = value;
                    this.RaisePropertyChanged("UserList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful {
            get {
                return this.WasSuccessfulField;
            }
            set {
                if ((this.WasSuccessfulField.Equals(value) != true)) {
                    this.WasSuccessfulField = value;
                    this.RaisePropertyChanged("WasSuccessful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Encap.IUserEncap")]
    public interface IUserEncap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/CreateUser", ReplyAction="http://tempuri.org/IUserEncap/CreateUserResponse")]
        SampleClient.Encap.UserResponse CreateUser(SampleClient.Encap.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/CreateUser", ReplyAction="http://tempuri.org/IUserEncap/CreateUserResponse")]
        System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> CreateUserAsync(SampleClient.Encap.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/UpdateUser", ReplyAction="http://tempuri.org/IUserEncap/UpdateUserResponse")]
        SampleClient.Encap.UserResponse UpdateUser(SampleClient.Encap.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/UpdateUser", ReplyAction="http://tempuri.org/IUserEncap/UpdateUserResponse")]
        System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> UpdateUserAsync(SampleClient.Encap.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/GetUser", ReplyAction="http://tempuri.org/IUserEncap/GetUserResponse")]
        SampleClient.Encap.UserResponse GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/GetUser", ReplyAction="http://tempuri.org/IUserEncap/GetUserResponse")]
        System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/ListUsers", ReplyAction="http://tempuri.org/IUserEncap/ListUsersResponse")]
        SampleClient.Encap.UserResponse ListUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserEncap/ListUsers", ReplyAction="http://tempuri.org/IUserEncap/ListUsersResponse")]
        System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> ListUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserEncapChannel : SampleClient.Encap.IUserEncap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserEncapClient : System.ServiceModel.ClientBase<SampleClient.Encap.IUserEncap>, SampleClient.Encap.IUserEncap {
        
        public UserEncapClient() {
        }
        
        public UserEncapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserEncapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserEncapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserEncapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SampleClient.Encap.UserResponse CreateUser(SampleClient.Encap.User user) {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> CreateUserAsync(SampleClient.Encap.User user) {
            return base.Channel.CreateUserAsync(user);
        }
        
        public SampleClient.Encap.UserResponse UpdateUser(SampleClient.Encap.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> UpdateUserAsync(SampleClient.Encap.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public SampleClient.Encap.UserResponse GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public SampleClient.Encap.UserResponse ListUsers() {
            return base.Channel.ListUsers();
        }
        
        public System.Threading.Tasks.Task<SampleClient.Encap.UserResponse> ListUsersAsync() {
            return base.Channel.ListUsersAsync();
        }
    }
}
